CREATE SCHEMA IF NOT EXISTS media;
CREATE SCHEMA IF NOT EXISTS metadata;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS characters;
CREATE SCHEMA IF NOT EXISTS external_links;
CREATE SCHEMA IF NOT EXISTS relations;
CREATE SCHEMA IF NOT EXISTS users;